platform :ios, '9.3'

source 'https://github.com/CocoaPods/Specs.git'

project 'LionheartCurrencyTextField.xcodeproj'

use_frameworks!

target 'LionheartCurrencyTextField_Example' do
  pod 'LionheartExtensions', '~> 3'
  pod 'LionheartCurrencyTextField', :path => '../'
end
